import { Inter } from 'next/font/google'
import './globals.css'
import { FileProvider } from './contexts/FileContext';
import { AppProvider } from './components/AppContext';
import { SessionProvider } from 'next-auth/react';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pretty PDF',
  description: 'Generated by Open AI',
  charset: 'UTF-8',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <FileProvider>
          <AppProvider>

            <div className='gradient' />
            {children}
          </AppProvider>

        </FileProvider>
      </body>
    </html>
  )
}
