import './globals.css'
import { FileProvider } from './contexts/FileContext';
import { AppProvider } from './components/AppContext';
import { SessionProvider } from 'next-auth/react';




export const metadata = {
  title: 'Pretty PDF',
  description: 'Generated by Open AI',
  charset: 'UTF-8',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body >
        <FileProvider>
          <AppProvider>

            <div className='gradient' />
            <div className='relative z-10 flex justify-center  flex-col max-w-7xl mx-auto sm:px-16 px-6;
'>

              {children}
            </div >
          </AppProvider>

        </FileProvider>
      </body>
    </html>
  )
}
